- .github/CONTRIBUTING.md
- layouts/default.vue
- layouts/print.vue
- nuxt.config.ts
本番のURLが決まったら改めて修正が必要
- close #7 
- URLを大阪開発用に修正
> 片っ端からURLを替えてみた。

- nuxt.config.ts
- close #9 
- googleAnalyticsの修正
> googleAnalyticsのID修正

- .github/CONTRIBUTING.md
- README.md
- layouts/default.vue
- layouts/print.vue
- nuxt.config.ts
> 本番用URL（https）に置き換え

- nuxt.config.ts
> CODEforOSAKAのトラッキングIDに変更

- data/news.json
> news.jsonに03/11分を追加（テスト）

- pages/about.vue
> お問い合わせ先を修正

- pages/about.vue
- close #60 
- お問い合わせ先の文言／URL変更
> お問い合わせ先の文言／URL変更

- pages/index.vue
> グラフ／表の並び替え

- components/DataTable.vue
- components/SvgCard.vue
- pages/index.vue
- utils/formatTable.ts
- close #59 
- グラフ／表の名称変更（svg以外）
> グラフ／表の名称変更（svg以外）

- nuxt.config.ts
- close #45 
- apple-mobile-web-app-titleを設定
> apple-mobile-web-app-titleを追加

- components/SideNavigation.vue
> LINEのリンクを追加

- components/DataView.vue
- utils/formatDate.ts
> グラフ下の日付フォーマットを変更

- components/TimeBarChart.vue
- pages/index.vue
- close #89 
- グラフ名変更（陰性確認済→陰性確認済（退院者累計））
> グラフ名変更（陰性確認済→陰性確認済（退院者累計））

- pages/about.vue
- close #96 
- リポジトリのリンク先を東京のリポジトリから大阪のリポジトリに変更。
> fix repository link

- components/PageHeader.vue
- close #105 
- 最終更新の日時フォーマットを「yyyy/mm/dd」に変更
> 最終更新の日時フォーマットを「yyyy/mm/dd」に変更

- nuxt.config.ts
- close #111 
- ヘッダから東京都twitter情報を削除
> ヘッダから東京都twitter情報を削除

- components/DataTable.vue
- pages/about.vue
- utils/formatTable.ts
> 「陽性者の属性」の表記修正

- components/ConfirmedCasesTable.vue
- close #124 
- 検査陽性者の状況の検査実施件数の単位を「人」から「件」に変更
> 検査陽性者の状況の検査実施件数の単位を「人」から「件」に変更

- components/SideNavigation.vue
- close #126 
- おおさか防災ネットTwitterリンクを追加
> おおさか防災ネットTwitterリンクを追加

- components/SideNavigation.vue
- pages/about.vue
多言語で表示できるようにしたい #110
- サイドナビゲーションの項目、「当サイトについて」が翻訳されるようにした
> Issue 110 lauguage selector

- README.md
- close #137
- README.mdの壊れていたリンク先を[こちら](https://covid19-osaka.info/)に変更しました。
> README.mdのリンク先を修正

- data/news.json
> 0327PM報道発表を反映

- components/SideNavigation.vue
- layouts/error.vue
多言語化した時のリンク先を指定言語のurlを付加する #151
- close #151
- 多言語化した時のリンク先を指定言語のurlを付加する
無し。
> 多言語化した時のリンク先を指定言語のurlを付加する

- utils/formatTable.ts
こちら、お手数をおかけしますが明日のデータ更新以降のマージでお願いします。
- close #161
- 属性情報に項番を追加
> 属性情報に項番を追加

- components/SideNavigation.vue
- close #194
- 東京に合わせて、上に移動する。
- サイドメニューの端に寄りすぎているので、隙間を開ける。
- フォントサイズを合わせる（仕様確認中）
PC
日本語
English
モバイル
日本語
English
> [WIP] 多言語対応選択メニューの表示

- .github/workflows/update.yml
- tool/config.py
- tool/main.py
- tool/util.py
- #32
- PR #188 
- ./tool/main.py を変更し、lastUpdate 以外で変更がない場合は lastUpdate も更新しないように変更
- GitHub Actioins の update.yml を変更し、プルリクを投げるように変更
- GitHub Actions により data-bot/development ブランチからプルリクが飛んでくる。マージするとこのブランチは自動で削除される。
> データ自動更新-3 自動プッシュからプルリクへ

- .eslintrc
- close #193
- ESLintとPrettierの設定が競合しCIが通らない問題を解消します
<details>
<summary>設定変更前のWarning</summary>
<pre>
<code>
npm run lint                                                                                                                                                                                
> covid19@1.0.0 lint /Users/mosugi/ghq/github.com/codeforosaka/covid19
> eslint './**/*.{js,ts,vue}' --fix
/Users/mosugi/ghq/github.com/codeforosaka/covid19/components/ConfirmedCasesTable.vue
218:5  warning  Prop "検査実施人数" is not in camelCase              vue/prop-name-casing
218:5  warning  Prop "検査実施人数" should define at least its type  vue/require-prop-types
219:5  warning  Prop "陽性物数" is not in camelCase                vue/prop-name-casing
219:5  warning  Prop "陽性物数" should define at least its …
> ESLintとPrettierの設定が競合しCIが通らない問題を解消

- data/news.json
> 0405報道発表を反映

- data/news.json
> 0407日中の報道発表を反映

- data/news.json
> 0407報道発表を反映

- data/news.json
> 0408報道提供を反映

- tool/main.py
> 「居住地」は調査中の場合は、調査中と表示するように修正

- data/news.json
> 0409報道発表を反映

- components/DataSelector.vue
- components/DataView.vue
- components/DataViewBasicInfoPanel.vue
- close #216 
- 英語のグラフで文字が重なる問題を修正しました
- https://github.com/tokyo-metropolitan-gov/covid19/issues/1146 から必要な箇所を移植して実装しています
英語
日本語
英語
日本語
> 英語のグラフで文字が重なる問題の修正

- components/SvgCard.vue
- pages/index.vue
- close #239 
- 「検査陽性者の状況」パネルに「※軽症・無症状には症状調査中を含む」という補足を追加しました。
> 「検査陽性者の状況」パネルに補足を追記

- data/news.json
> 0413報道発表のリンクを修正

- tool/main.py
- close #268 
- patients_and_inspectionsの「【公開OK】府HP用(陽性者ベース)」シートの「入退院の状況」（H列）に「療養」を含む場合、data.json の「退院」に「○」をつけるように変更
> "療養"の場合、陽性者の属性の「退院」を○にする

- components/ConfirmedCasesTable.vue
- close #280 
- #279 
- 検査実施件数のフォントサイズをインラインで 12px に変更。ギリギリ収まるようにした。
- 5桁での位置調整を指定した。
↑ 10000 件はテスト用のフェイクのデータです。
> 5桁の検査実施件数に対応

- pages/about.vue
> お問い合わせ先を多言語化

- components/WhatsNew.vue
- close #313 
- news.json で "url" を指定しなかった場合は `a` 要素ではなく代わりの `span` 要素を表示する
> 「最新のお知らせ」でリンク無しにできるように変更

- data/news.json
> 0423改修のお知らせ追加

- pages/index.vue
- close #322 
- 年代の値を「前から1文字目、後ろから2文字目」の間から取得するように変更
> 3桁の年代の表示を修正

- tool/main.py
- tool/util.py
> 療養者の情報を取得できるように

- tool/main.py
- #266 
- 入院中は「入院中」のみを集計するように修正
> 入院中は入院中のみを集計

- data/news.json
> 0427お知らせの更新

- components/DataTable.vue
- close #354 
- 年代のソートが正しく動作するようになった
> 年代のソートが正しく動作していない問題を修正

- layouts/error.vue
- close #366 
- エラーページが翻訳されていない問題を修正した
> エラーページが翻訳されていない問題を修正

- components/SideNavigation.vue
- close #391
- サイドバーの「知事からのメッセージ」のリンク先を以下に変更した (インデント調整は prettier による整形)
- http://www.pref.osaka.lg.jp/kikaku/message_governor/index.html
> サイドバーの「知事からのメッセージ」のリンク先を変更

- data/news.json
> お知らせに「モニタリング指標の状況」を追加

- components/TimeStackedBarChart.vue
- components/TimeStackedBarChart2.vue
- close #304
- 積み上げ棒グラフのツールチップが見切れないように修正した
> 積み上げ棒グラフのツールチップの見切れを修正

- components/ConfirmedCasesTable.vue
- tool/main.py
- tool/util.py
- utils/formatConfirmedCases.ts
- close #569 
- 「検査陽性者の状況」の「入院調整中」に内訳を追加する
> 569 mod details

- .github/workflows/auto_update.yml
- tool/request.py
- tool/requirements_req.txt
- #586 
- 大阪府が管理するkintoneから値を取得するように修正
- ※お試しなのでcommit、pushはあとから反映する
> Auto Update from kintone

- .github/workflows/auto_update.yml
> 取得元を間違えていたので修正

- .github/workflows/auto_update.yml
> 変更なしになったのでコミットを追加

- .github/workflows/auto_update.yml
> Excel版を取り込むために一旦自動反映を修正

- components/GraphicalMapCard.vue
凡例を地図で使用している色とリンクする
https://github.com/codeforosaka/covid19/issues/615
- 凡例の色を地図の色に合わせて変更しました。
> 凡例を地図で使用している色とリンクする

- components/GraphicalMapCard.vue
#635
#281 
- 市町村地図にマウスオーバー時のポップアップ（市名＋人数）を追加しました
> 市区町村地図にポップアップ（tooltip）を実装

- utils/formatTable.ts
- close #643 
- IE11で表示が遅い問題の対応
> IE11で表示が遅い問題の対応

- nuxt-i18n.config.ts
> プルダウンに简体中文の追加

- nuxt-i18n.config.ts
- #650 
- 他案件を本番反映するために一旦「简体中文」は非表示
> 一旦「简体中文」は非表示

- tool/request.py
> patients.csvの仕様変更

- nuxt-i18n.config.ts
> 本番に反映するので簡体字disable

- nuxt-i18n.config.ts
> サイドzh-cnをプルダウンに追加

- tool/request.py
> kintoneのURL変更

- tool/request.py
> クライアント証明書を利用した接続ができるようになったので修正

- data/news.json
> 最新のお知らせを修正

- components/GraphicalMapCard.vue
[市区町村地図]判例表示の閾値と実際の閾値が異なる #697
- close #697
- 閾値を合わせた
> [市区町村地図]判例表示の閾値と実際の閾値が異なる

- .github/workflows/auto_update.yml
> API tokenの設定が漏れていた

- components/ConfirmedCasesTable.vue
> 間違えて、数値を引っ張ってくるところを翻訳対象にしてしまったので修正

- components/RateChart.vue
- pages/index.vue
> 病床確保数の単位を「人」→「床」

- components/ScrollableChart.vue
yarn devを行うとserverのビルドに失敗する #756 
- close #756 
- ローカルで立ち上がらない原因を修正
> yarn devでビルドが失敗してしまう原因を修正
